use_frameworks!

platform :ios, '11.0'

target 'JccLibrary_Example' do
  pod 'JccLibrary', :path => '../'

  target 'JccLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
